//! Markdown report.

use super::{clean, stats::SessionStats};

pub fn render(stats: &SessionStats) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str("# vetto session report\n\n");
    out.push_str(&format!(
        "- tier: `{}` · net: `{}` · profile: `{}`\n",
        stats.tier,
        stats.net_mode,
        clean(&stats.profile)
    ));
    out.push_str(&format!(
        "- exit code: `{}` · duration: `{}s`\n\n",
        stats.exit_code, stats.duration_secs
    ));

    out.push_str("## Event counts\n\n");
    out.push_str("| event | count |\n|---|---|\n");
    for (kind, count) in &stats.counts {
        out.push_str(&format!("| {kind} | {count} |\n"));
    }
    out.push_str(&format!(
        "\nObserved file reads: {} · writes: {} (best-effort /proc polling).\n\n",
        stats.file_reads, stats.file_writes
    ));

    out.push_str("## Blocked attempts\n\n");
    if stats.blocked_attempts.is_empty() {
        out.push_str(
            "None observed. Observation channels are optional (see notices); \
             enforcement is active regardless.\n\n",
        );
    } else {
        out.push_str("| path | process | source | count |\n|---|---|---|---|\n");
        for b in &stats.blocked_attempts {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                clean(&b.path).replace('|', "\\|"),
                clean(&b.comm),
                clean(&b.source),
                b.count
            ));
        }
        out.push('\n');
    }

    out.push_str("## Network requests\n\n");
    if stats.net_requests.is_empty() {
        out.push_str("None (network is off by default).\n\n");
    } else {
        out.push_str("| host | port | decision |\n|---|---|---|\n");
        for r in &stats.net_requests {
            let decision = if r.allowed { "allow" } else { "DENIED" };
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                clean(&r.host),
                r.port,
                decision
            ));
        }
        out.push('\n');
    }

    out.push_str("## Notices\n\n");
    if stats.notices.is_empty() {
        out.push_str("- none\n");
    } else {
        for n in &stats.notices {
            out.push_str(&format!("- {}\n", clean(n)));
        }
    }

    out.push_str("\n---\nGenerated by vetto. Observations are BEST-EFFORT and never carry \
enforcement authority. Secret sanitizer: BEST-EFFORT.\n");
    out
}
