//! Interactive sandbox configurator (`vetto wizard`).

use std::io::{BufRead, IsTerminal, Write};
use std::path::Path;
use anyhow::{bail, Context, Result};
use clap::Args;

/// CLI arguments for `vetto wizard`.
#[derive(Args, Debug, Clone)]
pub struct WizardArgs {
    /// Target workspace directory (default: current directory)
    #[arg(value_name = "PATH", default_value = ".")]
    pub path: String,

    /// Non-interactive mode: accept recommended defaults without prompts
    #[arg(short = 'y', long = "yes")]
    pub yes: bool,

    /// Force overwrite of existing policy file if already present
    #[arg(short = 'f', long = "force")]
    pub force: bool,

    /// Security preset to configure (ignored in simplified wizard)
    #[arg(long, value_name = "PRESET")]
    pub preset: Option<String>,

    /// Target AI coding agent (e.g. claude, cursor, aider, opencode)
    #[arg(long, value_name = "AGENT")]
    pub agent: Option<String>,
}

pub fn run_wizard_cli(args: &WizardArgs) -> Result<()> {
    let stdin = std::io::stdin();
    let is_tty = stdin.is_terminal();
    let mut reader = stdin.lock();
    let mut writer = std::io::stdout();
    run_wizard_flow(args, is_tty, &mut reader, &mut writer)
}

pub fn run_wizard_flow(
    args: &WizardArgs,
    is_tty: bool,
    reader: &mut impl BufRead,
    writer: &mut impl Write,
) -> Result<()> {
    let root = Path::new(&args.path);
    let root_canon = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());

    let target_dir = root_canon.join(".vetto");
    let target_policy_path = target_dir.join("policy.toml");

    if target_policy_path.exists() && !args.force {
        bail!(
            "policy file already exists at {} (use -f / --force to overwrite)",
            target_policy_path.display()
        );
    }

    let is_interactive = !args.yes && is_tty;

    let (agent_slug, net_mode, protect) = if is_interactive {
        writeln!(writer, "╔════════════════════════════════════════════════════════════════╗")?;
        writeln!(writer, "║                  Vetto Interactive Wizard                      ║")?;
        writeln!(writer, "╚════════════════════════════════════════════════════════════════╝")?;
        writeln!(writer)?;

        write!(writer, "1. Какой агент? (claude/cursor/aider/opencode) [claude]: ")?;
        writer.flush()?;
        let mut agent = String::new();
        reader.read_line(&mut agent)?;
        let agent_trim = agent.trim();
        let agent_slug = if agent_trim.is_empty() {
            "claude".to_string()
        } else {
            agent_trim.to_string()
        };

        write!(writer, "2. Сеть? (full/allowlist/off/ask) [allowlist]: ")?;
        writer.flush()?;
        let mut net = String::new();
        reader.read_line(&mut net)?;
        let net_trim = net.trim();
        let net_mode = if net_trim.is_empty() {
            "allowlist".to_string()
        } else {
            net_trim.to_string()
        };

        write!(writer, "3. Защита секретов? (yes/no) [yes]: ")?;
        writer.flush()?;
        let mut sec = String::new();
        reader.read_line(&mut sec)?;
        let sec_trim = sec.trim().to_lowercase();
        let protect = sec_trim.is_empty() || sec_trim == "y" || sec_trim == "yes";

        (agent_slug, net_mode, protect)
    } else {
        let agent_slug = args.agent.clone().unwrap_or_else(|| "claude".to_string());
        (agent_slug, "allowlist".to_string(), true)
    };

    let toml = format!(
        r#"# policy.toml - Vetto Security Policy
# Generated by `vetto wizard`

[metadata]
name = "vetto-project"
description = "Vetto security policy for {}"
extends = ["default", "{}"]

[security]
auto_deny_secrets = {}

[filesystem]
allow_write = [
  "$PROJECT",
  "/tmp",
]
deny_write = [
  "$PROJECT/.git",
]
allow_read = [
  "$PROJECT",
]

[network]
mode = "{}"
"#,
        agent_slug, agent_slug, protect, net_mode
    );

    std::fs::create_dir_all(&target_dir)
        .with_context(|| format!("failed to create directory {}", target_dir.display()))?;
    std::fs::write(&target_policy_path, &toml)
        .with_context(|| format!("failed to write policy to {}", target_policy_path.display()))?;

    let display_path = if args.path == "." || args.path.is_empty() {
        ".vetto/policy.toml".to_string()
    } else {
        target_policy_path.display().to_string()
    };

    writeln!(writer, "✓ Vetto security policy generated at {}", display_path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::io::Cursor;
    use std::path::PathBuf;

    fn temp_test_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "vetto-wizard-test-{name}-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_wizard_non_interactive_generates_policy() {
        let dir = temp_test_dir("non-interactive");
        let args = WizardArgs {
            path: dir.to_str().unwrap().to_string(),
            yes: true,
            force: false,
            preset: None,
            agent: Some("cursor".to_string()),
        };
        let mut writer = Vec::new();
        let mut reader = Cursor::new(b"");
        run_wizard_flow(&args, false, &mut reader, &mut writer).unwrap();

        let policy_path = dir.join(".vetto").join("policy.toml");
        assert!(policy_path.exists());
        let content = fs::read_to_string(&policy_path).unwrap();
        assert!(content.contains(r#"extends = ["default", "cursor"]"#));
        assert!(content.contains(r#"auto_deny_secrets = true"#));
        assert!(content.contains(r#"mode = "allowlist""#));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_wizard_interactive_flow() {
        let dir = temp_test_dir("interactive");
        let args = WizardArgs {
            path: dir.to_str().unwrap().to_string(),
            yes: false,
            force: false,
            preset: None,
            agent: None,
        };
        let input = "aider\nask\nno\n";
        let mut reader = Cursor::new(input.as_bytes());
        let mut writer = Vec::new();

        run_wizard_flow(&args, true, &mut reader, &mut writer).unwrap();

        let policy_path = dir.join(".vetto").join("policy.toml");
        let content = fs::read_to_string(&policy_path).unwrap();
        assert!(content.contains(r#"extends = ["default", "aider"]"#));
        assert!(content.contains(r#"auto_deny_secrets = false"#));
        assert!(content.contains(r#"mode = "ask""#));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_wizard_respects_force_flag() {
        let dir = temp_test_dir("respects-force");
        let args = WizardArgs {
            path: dir.to_str().unwrap().to_string(),
            yes: true,
            force: false,
            preset: None,
            agent: None,
        };

        let mut writer = Vec::new();
        let mut reader = Cursor::new(b"");
        assert!(run_wizard_flow(&args, false, &mut reader, &mut writer).is_ok());

        let err = run_wizard_flow(&args, false, &mut reader, &mut writer).unwrap_err();
        assert!(err.to_string().contains("already exists"));

        let force_args = WizardArgs {
            force: true,
            ..args
        };
        assert!(run_wizard_flow(&force_args, false, &mut reader, &mut writer).is_ok());

        let _ = fs::remove_dir_all(&dir);
    }
}
