//! Seatbelt (sandbox-exec) profile generation from a vetto Policy.
//!
//! SBPL semantics: (deny default) first, explicit allows for the policy
//! roots, then TRAILING (deny ...) rules carve secrets out of allowed trees
//! (last matching rule wins) — the macOS counterpart of the Linux mount
//! overlay trick, minus overlays.

use crate::config::NetMode;
use crate::policy::Policy;

pub fn generate(policy: &Policy, net: &NetMode) -> String {
    let mut sb = String::with_capacity(2048);
    sb.push_str("(version 1)\n(deny default)\n");

    for p in &policy.allow_read {
        sb.push_str(&format!(
            "(allow file-read* (subpath \"{}\"))\n",
            sb_escape(&p.display().to_string())
        ));
    }
    for p in &policy.allow_write {
        let s = sb_escape(&p.display().to_string());
        sb.push_str(&format!("(allow file-read* (subpath \"{s}\"))\n"));
        sb.push_str(&format!("(allow file-write* (subpath \"{s}\"))\n"));
    }

    // Carve the deny set out of allowed trees: trailing denies win in SBPL.
    for d in &policy.deny_resolved {
        let s = sb_escape(&d.path.display().to_string());
        sb.push_str(&format!("(deny file-read* (subpath \"{s}\"))\n"));
        sb.push_str(&format!("(deny file-write* (subpath \"{s}\"))\n"));
    }

    match net {
        NetMode::Off => sb.push_str("(deny network*)\n"),
        // Relay modes are Linux-only. On macOS they fail closed as ordinary
        // network-off sessions if a caller reaches profile generation.
        NetMode::Allowlist(_) | NetMode::Strict(_) => sb.push_str("(deny network*)\n"),
    }

    sb.push_str("\n; generated by vetto — see SECURITY.md for honest limits\n");
    sb
}

fn sb_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
